// Mocks generated by Mockito 5.4.6 from annotations
// in samurai_studios/test/features/characters/data/repositories/character_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:samurai_studios/features/characters/data/datasources/character_remote_datasource.dart'
    as _i3;
import 'package:samurai_studios/features/characters/data/models/character_response_dto.dart'
    as _i2;
import 'package:samurai_studios/features/characters/data/models/episode_dto.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCharacterResponseDto_0 extends _i1.SmartFake
    implements _i2.CharacterResponseDto {
  _FakeCharacterResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CharacterRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCharacterRemoteDataSource extends _i1.Mock
    implements _i3.CharacterRemoteDataSource {
  MockCharacterRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CharacterResponseDto> getCharacters({int? page = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#getCharacters, [], {#page: page}),
            returnValue: _i4.Future<_i2.CharacterResponseDto>.value(
              _FakeCharacterResponseDto_0(
                this,
                Invocation.method(#getCharacters, [], {#page: page}),
              ),
            ),
          )
          as _i4.Future<_i2.CharacterResponseDto>);

  @override
  _i4.Future<List<_i5.EpisodeDto>> getEpisodes(List<String>? episodeUrls) =>
      (super.noSuchMethod(
            Invocation.method(#getEpisodes, [episodeUrls]),
            returnValue: _i4.Future<List<_i5.EpisodeDto>>.value(
              <_i5.EpisodeDto>[],
            ),
          )
          as _i4.Future<List<_i5.EpisodeDto>>);
}
